### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by ahmed-alii** [akshaybahadur21/QuickDraw#2]
While trying to run loadData.py file, I received following errors:

```
Traceback (most recent call last):
  File "/Users/ahmed/Downloads/QuickDraw-master/LoadData.py", line 29, in <module>
    features, labels = load_data()
  File "/Users/ahmed/Downloads/QuickDraw-master/LoadData.py", line 16, in load_data
    x = np.load(file)
  File "/Users/ahmed/.conda/envs/QuickDraw-master/lib/python3.6/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data\\full-numpy_bitmap-dog.npy'

```
Note: I am working on a mac. I removed the location (F:\\blablabla)

**Comment by ahmed-alii** [comment]
I figured it out and its resolved. Just use single forward slash for mac users.
