### ISSUE TITLE
QD_Trainer Issue

### ISSUE THREAD

**Issue by mm26649** [akshaybahadur21/QuickDraw#5]
Error when i try to run QD_trainer.py

Traceback (most recent call last):
  File "C:\Python37\QuickDraw-master\QD_trainer.py", line 75, in <module>
    main()
  File "C:\Python37\QuickDraw-master\QD_trainer.py", line 71, in main
    callbacks=[TensorBoard(log_dir="QuickDraw")])
  File "C:\Python37\lib\site-packages\keras\engine\training.py", line 952, in fit
    batch_size=batch_size)
  File "C:\Python37\lib\site-packages\keras\engine\training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "C:\Python37\lib\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
**ValueError: Error when checking target: expected dense_3 to have shape (15,) but got array with shape (6,)**

im facing this error when i run the code, Could you help me fix it?

**Comment by akshaybahadur21** [comment]
@mm26649 - Have you changed the shape of data.
Ideally the data in dense_3 should be have 15 rows but you are getting 6 rows

**Comment by barslmn** [comment]
Try changing `num_of_classes` variable  in QD_Trainer.py

**Comment by akshaybahadur21** [comment]
Marking as resolved.
